In [1]:
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
x = torch.tensor([-1,0,1,2,3,4,5])

In [4]:
relu = nn.ReLU()

In [5]:
relu(x)

tensor([0, 0, 1, 2, 3, 4, 5])

In [6]:
x

tensor([-1,  0,  1,  2,  3,  4,  5])

In [7]:
relu = nn.ReLU(inplace=True)
relu(x)

tensor([0, 0, 1, 2, 3, 4, 5])

In [8]:
x

tensor([0, 0, 1, 2, 3, 4, 5])